Update test3

diff --git a/test3 b/test3
--- a/test3
+++ b/test3
@@ -1,20 +1,78 @@
+stages:
+  - build
+  - test
+  - deploy
+  - teardown
+
+build-api:
+  image: docker:20
+  stage: build
+  before_script:
+    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
+  script:
+    - if [[ $CI_COMMIT_BRANCH = $CI_DEFAULT_BRANCH ]]; then DOCKER_TAG=latest; else DOCKER_TAG="$CI_COMMIT_REF_NAME"; fi
+    - echo "building $CI_REGISTRY_IMAGE:$DOCKER_TAG"
+    - docker buildx build --cache-from=$CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$DOCKER_TAG --push --target=base .
+    - echo "building $CI_REGISTRY_IMAGE:test-$DOCKER_TAG"
+    - docker buildx build --cache-from=$CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:test-$DOCKER_TAG --push --target=test .
+  rules:
+    - if: $CI_MERGE_REQUEST_ID
+      changes:
+        - Dockerfile
+        - "*.py"
+        - requirements.txt
+        - requirements-dev.txt
+    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
+      changes:
+        - Dockerfile
+        - "*.py"
+        - requirements.txt
+        - requirements-dev.txt    
+
+build-utils:
+  image: docker:20
+  stage: build
+  before_script:
+    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
+  script:
+    - echo "building $CI_REGISTRY_IMAGE/utils:latest"
+    - docker buildx build --cache-from=$CI_REGISTRY_IMAGE/utils:latest -t $CI_REGISTRY_IMAGE/utils:latest --push -f Dockerfile-utils .
+  rules:
+    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
+      changes:
+        - Dockerfile-utils  
+
+unit-tests:
+  image: $CI_REGISTRY_IMAGE:test-$CI_COMMIT_REF_NAME
+  stage: test 
+  script:
+    - pytest --cov --cov-fail-under=90
+  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
+  rules:
+    - if: $CI_MERGE_REQUEST_ID #job runs in MR pipelines.
+      changes:
+        - Dockerfile
+        - "*.py"
+        - requirements.txt
+        - requirements-dev.txt
 deploy:
   image: $CI_REGISTRY_IMAGE/utils:latest
   stage: deploy
   rules:
     - if: $CI_MERGE_REQUEST_ID
     - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
+  environment:
+    name: review/$CI_COMMIT_REF_NAME
+    url: https://$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.cc25.chasacademy.dev/docs
+    on_stop: stop_review
   script:
     - |
       set -e
       export PORTAINER_TOKEN=$(curl -s -X POST "https://portainer.cc25.chasacademy.dev/api/auth" --json '{"username": "'$PORTAINER_USER'", "password": "'$PORTAINER_PASSWORD'"}' | jq -r '.jwt')
-      
-      # Slugifiera STACK_NAME så den är kompatibel med Traefik och labels
       RAW_STACK_NAME="$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME"
-      STACK_NAME=$(echo "$RAW_STACK_NAME" | tr '/_' '-' | tr '[:upper:]' '[:lower:]')
+      STACK_NAME=$(echo "$RAW_STACK_NAME" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
       export STACK_NAME
       echo "Stack: $STACK_NAME"
-
       if [[ "$CI_COMMIT_REF_NAME" = $CI_DEFAULT_BRANCH ]]; then DOCKER_TAG=latest; else DOCKER_TAG=$CI_COMMIT_REF_NAME; fi
       export DOCKER_TAG
       echo "Docker tag: $DOCKER_TAG"
@@ -42,5 +100,50 @@ deploy:
           -F SwarmID="$SWARM_ID" \
           -F file=@deployable-compose.yml | jq 
       else 
-        echo "I need to update the stack" 
+        echo "Updating stack $STACK_ID $STACK_NAME"
+        export COMPOSE_CONTENTS=$(cat deployable-compose.yml)
+        export JSON_PAYLOAD=$(jq --null-input --arg compose "$COMPOSE_CONTENTS" '{"prune": true, "pullImage": true, "stackFileContent": $compose}')
+        echo "$JSON_PAYLOAD"
+        curl -X PUT https://portainer.cc25.chasacademy.dev/api/stacks/$STACK_ID?endpointId=$ENDPOINT_ID -H "Authorization: Bearer $PORTAINER_TOKEN" --json "$JSON_PAYLOAD" | jq
+      fi
+
+stop_review:
+  stage: teardown
+  image: $CI_REGISTRY_IMAGE/utils:latest
+  environment:
+    name: review/$CI_COMMIT_REF_NAME
+    action: stop
+  rules:
+    - if: $CI_MERGE_REQUEST_ID
+      when: manual
+  script:
+    - |
+      set -e
+      export PORTAINER_TOKEN=$(curl -s -X POST "https://portainer.cc25.chasacademy.dev/api/auth" --json '{"username": "'$PORTAINER_USER'", "password": "'$PORTAINER_PASSWORD'"}' | jq -r '.jwt')
+      
+      RAW_STACK_NAME="$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME"
+      STACK_NAME=$(echo "$RAW_STACK_NAME" | tr '/_' '-' | tr '[:upper:]' '[:lower:]')
+      export STACK_NAME
+      echo "Stack: $STACK_NAME"
+
+      if [[ "$CI_COMMIT_REF_NAME" = $CI_DEFAULT_BRANCH ]]; then DOCKER_TAG=latest; else DOCKER_TAG=$CI_COMMIT_REF_NAME; fi
+      echo "Docker tag: $DOCKER_TAG"
+
+      export ENDPOINT_ID=$(curl -s https://portainer.cc25.chasacademy.dev/api/endpoints -H "Authorization: Bearer $PORTAINER_TOKEN" | jq '.[] | select(.Name == "primary") | .Id')
+      echo "Endpoint: $ENDPOINT_ID"
+
+      export SWARM_ID=$(curl -s https://portainer.cc25.chasacademy.dev/api/endpoints -H "Authorization: Bearer $PORTAINER_TOKEN" | jq '.[] | select(.Name == "primary") | .Snapshots[0].DockerSnapshotRaw.Info.Swarm.Cluster.ID' -r)
+      echo "Swarm: $SWARM_ID"
+
+      echo "Checking if STACK_NAME is present..."
+      STACK_ID=$(curl -s https://portainer.cc25.chasacademy.dev/api/stacks -H "Authorization: Bearer $PORTAINER_TOKEN" | jq '.[] | select(.Name == "'$STACK_NAME'") | .Id')
+
+      echo "Stack id: \"$STACK_ID\""
+      if [[ "$STACK_ID" = "" ]]
+      then 
+        echo "Stack $STACK_ID $STACK_NAME not found!"
+        exit 1
+      else 
+        echo "Deleting stack $STACK_ID $STACK_NAME"
+        curl -X DELETE https://portainer.cc25.chasacademy.dev/api/stacks/$STACK_ID?endpointId=$ENDPOINT_ID -H "Authorization: Bearer $PORTAINER_TOKEN"
       fi
